# Generated by Django 4.2.6 on 2023-11-01 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concierto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banda', models.CharField(max_length=30)),
                ('genero', models.TextField()),
                ('preciodeentrada', models.IntegerField()),
            ],
        ),
    ]
