# Generated by Django 4.2.6 on 2023-11-01 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concierto',
            old_name='preciodeentrada',
            new_name='precioEntrada',
        ),
    ]
