# Generated by Django 4.2.6 on 2023-11-08 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_rename_preciodeentrada_concierto_precioentrada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Direccion', models.TextField()),
                ('capacidad', models.IntegerField()),
            ],
        ),
    ]
